### ISSUE TITLE
Raycasting causes exception in server tick loop

### ISSUE THREAD

**Issue by prodigylock** [Stick404/PortalHexAddon#1]
Game seems to crash when trying archers distillation.
Crash log below:
[crash-2024-04-20_14.59.59-server.txt](https://github.com/Stick404/PortalHexAddon/files/15048075/crash-2024-04-20_14.59.59-server.txt)

Full log below:
[latest.log](https://github.com/Stick404/PortalHexAddon/files/15048080/latest.log)

**Comment by prodigylock** [comment]
Immersive portals was not installed.
Suggestion:
Throw error if not detected.

**Comment by Stick404** [comment]
https://github.com/Stick404/PortalHexAddon/commit/bbca8a6e5004f69ee4c416a4e0902a0ddd561ac5 Just fixed this
