### ISSUE TITLE
Server Hosting Causing player data crashing

### ISSUE THREAD

**Issue by KinglessBat** [Stick404/PortalHexAddon#5]
I am hosting the mod on a minecraft server. I have had several players go through portals made with hexway suddenly crash at random (the portals work before for them) and then whenever they try to rejoin their minecraft crashes. I have two logs linked below from two players. When I try to replicate the crashes I can't

https://mclo.gs/z5Kqq0o

https://mclo.gs/C8LPv22

**Comment by Stick404** [comment]
Just as a warning, Byte Code Dumps (like these) can be used to get into player's accounts. I think mclo.gs may hide them, but I don't know. Also, it appears to be an Immersive Portal's rendering bug, so best to make a private error with them. I am sorry I can't help more
