### ISSUE TITLE
Get Output Info seems inconsistent

### ISSUE THREAD

**Issue by beholderface** [Stick404/PortalHexAddon#6]
Sometimes it returns the paired portal as an entity, sometimes it returns its position. I have no idea what factors contribute to this, nor is there anything in the book to indicate what they are. This can be dealt with by checking the type of the returned iota, but IMO this shouldn't be necessary.
I suggest splitting it into two patterns: One that just returns the paired portal's position, and another that returns it as an entity (or NULL if it cannot for some reason).

**Comment by Stick404** [comment]
Returning coordinate happens when OutputInfo is used on a 1-way portal. However, it seems like I forgot to say that in the Hex Book, will be fixed in the next update.
